
# the name of Camel
camel.springboot.name = MyCamel
camel.rest.component=servlet
camel.rest.binding-mode=json
camel.servlet.mapping.context-path=/api/*

logging.level.org.apache.camel.component.servlet=INFO
logging.level.org.apache.camel=INFO
logging.level.org.springframework.web=INFO
logging.level.dev.vsviniciuslima=DEBUG

# what to say
server.port=8081

newcon.error-handler.enabled = true
newcon.error-handler.target-hosts = localhost

# Configurações da API
api.base-url=http://localhost:8080

spring.web.resources.add-mappings=false

# to automatic shutdown the JVM after a period of time
#camel.springboot.duration-max-seconds=60
#camel.springboot.duration-max-messages=100

# add for example: &repeatCount=5 to the timer endpoint to make Camel idle
#camel.springboot.duration-max-idle-seconds=15

# expose actuator endpoint via HTTP
management.endpoints.web.exposure.include=info,health,camelroutes

# turn on actuator health check
management.endpoint.health.enabled = true

# allow to obtain basic information about camel routes (read only mode)
management.endpoint.camelroutes.enabled = true
management.endpoint.camelroutes.read-only = true

# to configure logging levels
#logging.level.org.springframework = INFO
#logging.level.org.apache.camel.spring.boot = INFO
#logging.level.org.apache.camel.impl = DEBUG
#logging.level.sample.camel = DEBUG
#logging.level.org.apache.camel= DEBUG